//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KoBeLUAdmin.Localization {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KoBeLUAdmin.Localization.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Audio ähnelt.
        /// </summary>
        public static string buttonAudio {
            get {
                return ResourceManager.GetString("buttonAudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Background Screenshot ähnelt.
        /// </summary>
        public static string buttonBackgroundScreenshot {
            get {
                return ResourceManager.GetString("buttonBackgroundScreenshot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cancel ähnelt.
        /// </summary>
        public static string buttonCancel {
            get {
                return ResourceManager.GetString("buttonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Circle ähnelt.
        /// </summary>
        public static string buttonCircle {
            get {
                return ResourceManager.GetString("buttonCircle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Pause / Continue ähnelt.
        /// </summary>
        public static string buttonContinueRecording {
            get {
                return ResourceManager.GetString("buttonContinueRecording", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Delete ähnelt.
        /// </summary>
        public static string buttonDelete {
            get {
                return ResourceManager.GetString("buttonDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Deselect all ähnelt.
        /// </summary>
        public static string buttonDeselectAll {
            get {
                return ResourceManager.GetString("buttonDeselectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Detect zone ähnelt.
        /// </summary>
        public static string buttonDetectZone {
            get {
                return ResourceManager.GetString("buttonDetectZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Forward ähnelt.
        /// </summary>
        public static string buttonDown {
            get {
                return ResourceManager.GetString("buttonDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ext. Visualization ähnelt.
        /// </summary>
        public static string buttonExternalVisualization {
            get {
                return ResourceManager.GetString("buttonExternalVisualization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Filter ähnelt.
        /// </summary>
        public static string buttonFilter {
            get {
                return ResourceManager.GetString("buttonFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Find ID ähnelt.
        /// </summary>
        public static string buttonFindID {
            get {
                return ResourceManager.GetString("buttonFindID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Image ähnelt.
        /// </summary>
        public static string buttonImage {
            get {
                return ResourceManager.GetString("buttonImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Load ähnelt.
        /// </summary>
        public static string buttonLoad {
            get {
                return ResourceManager.GetString("buttonLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Load assembly zone ähnelt.
        /// </summary>
        public static string buttonLoadAssemblyZone {
            get {
                return ResourceManager.GetString("buttonLoadAssemblyZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Load box layout ähnelt.
        /// </summary>
        public static string buttonLoadBoxLayout {
            get {
                return ResourceManager.GetString("buttonLoadBoxLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Load detection zone layout ähnelt.
        /// </summary>
        public static string buttonLoadDetectionZoneLayout {
            get {
                return ResourceManager.GetString("buttonLoadDetectionZoneLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Load object zone ähnelt.
        /// </summary>
        public static string buttonLoadObjectZone {
            get {
                return ResourceManager.GetString("buttonLoadObjectZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Load scene ähnelt.
        /// </summary>
        public static string buttonLoadScene {
            get {
                return ResourceManager.GetString("buttonLoadScene", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die New scene ähnelt.
        /// </summary>
        public static string buttonNewScene {
            get {
                return ResourceManager.GetString("buttonNewScene", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Play 2D record ähnelt.
        /// </summary>
        public static string buttonPlay2DRecord {
            get {
                return ResourceManager.GetString("buttonPlay2DRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Play 3D record ähnelt.
        /// </summary>
        public static string buttonPlay3DRecord {
            get {
                return ResourceManager.GetString("buttonPlay3DRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Polygon ähnelt.
        /// </summary>
        public static string buttonPolygon {
            get {
                return ResourceManager.GetString("buttonPolygon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Quit assembly ähnelt.
        /// </summary>
        public static string buttonQuitAssembly {
            get {
                return ResourceManager.GetString("buttonQuitAssembly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Record 2D gesture ähnelt.
        /// </summary>
        public static string buttonRecord2DGesture {
            get {
                return ResourceManager.GetString("buttonRecord2DGesture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Record 3D gesture ähnelt.
        /// </summary>
        public static string buttonRecord3DGesture {
            get {
                return ResourceManager.GetString("buttonRecord3DGesture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Record 3D profile ähnelt.
        /// </summary>
        public static string buttonRecord3DProfile {
            get {
                return ResourceManager.GetString("buttonRecord3DProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Rectangle ähnelt.
        /// </summary>
        public static string buttonRectangle {
            get {
                return ResourceManager.GetString("buttonRectangle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Remove ähnelt.
        /// </summary>
        public static string buttonRemove {
            get {
                return ResourceManager.GetString("buttonRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Rotation ähnelt.
        /// </summary>
        public static string buttonRotation {
            get {
                return ResourceManager.GetString("buttonRotation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save ähnelt.
        /// </summary>
        public static string buttonSave {
            get {
                return ResourceManager.GetString("buttonSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save assembly zone ähnelt.
        /// </summary>
        public static string buttonSaveAssemblyZone {
            get {
                return ResourceManager.GetString("buttonSaveAssemblyZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save box layout ähnelt.
        /// </summary>
        public static string buttonSaveBoxLayout {
            get {
                return ResourceManager.GetString("buttonSaveBoxLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save detection zone layout ähnelt.
        /// </summary>
        public static string buttonSaveDetectionZoneLayout {
            get {
                return ResourceManager.GetString("buttonSaveDetectionZoneLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save scene ähnelt.
        /// </summary>
        public static string buttonSaveScene {
            get {
                return ResourceManager.GetString("buttonSaveScene", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Scan object ähnelt.
        /// </summary>
        public static string buttonScanObjects {
            get {
                return ResourceManager.GetString("buttonScanObjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Screenshot ähnelt.
        /// </summary>
        public static string buttonScreenshot {
            get {
                return ResourceManager.GetString("buttonScreenshot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Select all ähnelt.
        /// </summary>
        public static string buttonSelectAll {
            get {
                return ResourceManager.GetString("buttonSelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Snapshot ähnelt.
        /// </summary>
        public static string buttonSnapshot {
            get {
                return ResourceManager.GetString("buttonSnapshot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Start assembly ähnelt.
        /// </summary>
        public static string buttonStartAssembly {
            get {
                return ResourceManager.GetString("buttonStartAssembly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Start recording ähnelt.
        /// </summary>
        public static string buttonStartRecording {
            get {
                return ResourceManager.GetString("buttonStartRecording", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Start recording video ähnelt.
        /// </summary>
        public static string buttonStartRecordingVideo {
            get {
                return ResourceManager.GetString("buttonStartRecordingVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Stop recording ähnelt.
        /// </summary>
        public static string buttonStopRecording {
            get {
                return ResourceManager.GetString("buttonStopRecording", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Stop recording video ähnelt.
        /// </summary>
        public static string buttonStopRecordingVideo {
            get {
                return ResourceManager.GetString("buttonStopRecordingVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Text ähnelt.
        /// </summary>
        public static string buttonText {
            get {
                return ResourceManager.GetString("buttonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Text viewer ähnelt.
        /// </summary>
        public static string buttonTextViewer {
            get {
                return ResourceManager.GetString("buttonTextViewer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Back ähnelt.
        /// </summary>
        public static string buttonUp {
            get {
                return ResourceManager.GetString("buttonUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Video ähnelt.
        /// </summary>
        public static string buttonVideo {
            get {
                return ResourceManager.GetString("buttonVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Enable automatic Adaptivity ähnelt.
        /// </summary>
        public static string checkboxAdaptivityEnabled {
            get {
                return ResourceManager.GetString("checkboxAdaptivityEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Display visual feedback ähnelt.
        /// </summary>
        public static string checkboxDisplayVisualFeedback {
            get {
                return ResourceManager.GetString("checkboxDisplayVisualFeedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Enable edit mode? ähnelt.
        /// </summary>
        public static string checkboxEnableEditMode {
            get {
                return ResourceManager.GetString("checkboxEnableEditMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Enable Ensenso Smoothing ähnelt.
        /// </summary>
        public static string checkboxEnableEnsensoSmoothing {
            get {
                return ResourceManager.GetString("checkboxEnableEnsensoSmoothing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Enable box fault detection ähnelt.
        /// </summary>
        public static string checkboxEnableFaultDetection {
            get {
                return ResourceManager.GetString("checkboxEnableFaultDetection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Enable gesture mapping? ähnelt.
        /// </summary>
        public static string checkboxEnableGestureMapping {
            get {
                return ResourceManager.GetString("checkboxEnableGestureMapping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Free space ähnelt.
        /// </summary>
        public static string checkboxFreeSpace {
            get {
                return ResourceManager.GetString("checkboxFreeSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Invert display? ähnelt.
        /// </summary>
        public static string checkboxInvertDisplay {
            get {
                return ResourceManager.GetString("checkboxInvertDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Loop play ähnelt.
        /// </summary>
        public static string checkboxLoopPlay2DRecord {
            get {
                return ResourceManager.GetString("checkboxLoopPlay2DRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Loop play ähnelt.
        /// </summary>
        public static string checkboxLoopPlay3DRecord {
            get {
                return ResourceManager.GetString("checkboxLoopPlay3DRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Object mapping ähnelt.
        /// </summary>
        public static string checkboxObjectMapping {
            get {
                return ResourceManager.GetString("checkboxObjectMapping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Project visual feedback ähnelt.
        /// </summary>
        public static string checkboxProjectVisualFeedback {
            get {
                return ResourceManager.GetString("checkboxProjectVisualFeedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Recognize objects ähnelt.
        /// </summary>
        public static string checkboxRecognizeObjects {
            get {
                return ResourceManager.GetString("checkboxRecognizeObjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Show criticals ähnelt.
        /// </summary>
        public static string checkboxShowCriticals {
            get {
                return ResourceManager.GetString("checkboxShowCriticals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Show demo animation? ähnelt.
        /// </summary>
        public static string checkboxShowDemoAnimation {
            get {
                return ResourceManager.GetString("checkboxShowDemoAnimation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Show errors ähnelt.
        /// </summary>
        public static string checkboxShowErrors {
            get {
                return ResourceManager.GetString("checkboxShowErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Show FPS on screen? ähnelt.
        /// </summary>
        public static string checkboxShowFPSOnScreen {
            get {
                return ResourceManager.GetString("checkboxShowFPSOnScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Show informations ähnelt.
        /// </summary>
        public static string checkboxShowInformations {
            get {
                return ResourceManager.GetString("checkboxShowInformations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Show warnings ähnelt.
        /// </summary>
        public static string checkboxShowWarnings {
            get {
                return ResourceManager.GetString("checkboxShowWarnings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Start projection ähnelt.
        /// </summary>
        public static string checkboxStartProjection {
            get {
                return ResourceManager.GetString("checkboxStartProjection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Stream scenedata via UDP to IP ähnelt.
        /// </summary>
        public static string checkboxStreamUDP {
            get {
                return ResourceManager.GetString("checkboxStreamUDP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Track object ähnelt.
        /// </summary>
        public static string checkboxTrackObject {
            get {
                return ResourceManager.GetString("checkboxTrackObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Detect touch ähnelt.
        /// </summary>
        public static string detectTouch {
            get {
                return ResourceManager.GetString("detectTouch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Display Touch Coordinates ähnelt.
        /// </summary>
        public static string displayTouchDebugCoordinates {
            get {
                return ResourceManager.GetString("displayTouchDebugCoordinates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Display touch video feed ähnelt.
        /// </summary>
        public static string displayTouchVideoFeed {
            get {
                return ResourceManager.GetString("displayTouchVideoFeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Display WPF projection plane ähnelt.
        /// </summary>
        public static string displayWPFProjectionPlane {
            get {
                return ResourceManager.GetString("displayWPFProjectionPlane", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Actions ähnelt.
        /// </summary>
        public static string labelActions {
            get {
                return ResourceManager.GetString("labelActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Adaptivity Threshold to Hard ähnelt.
        /// </summary>
        public static string labelAdaptivityThresholdHard {
            get {
                return ResourceManager.GetString("labelAdaptivityThresholdHard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Adaptivity Threshold to Medium ähnelt.
        /// </summary>
        public static string labelAdaptivityThresholdMedium {
            get {
                return ResourceManager.GetString("labelAdaptivityThresholdMedium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Box feedback timeout ähnelt.
        /// </summary>
        public static string labelBoxFeedbackTimeout {
            get {
                return ResourceManager.GetString("labelBoxFeedbackTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Colorframe offset X: ähnelt.
        /// </summary>
        public static string labelColorframeOffsetX {
            get {
                return ResourceManager.GetString("labelColorframeOffsetX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Colorframe offset Y: ähnelt.
        /// </summary>
        public static string labelColorframeOffsetY {
            get {
                return ResourceManager.GetString("labelColorframeOffsetY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Count of Rectangle ähnelt.
        /// </summary>
        public static string labelCountOfRectangle {
            get {
                return ResourceManager.GetString("labelCountOfRectangle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Current step ähnelt.
        /// </summary>
        public static string labelCurrentStep {
            get {
                return ResourceManager.GetString("labelCurrentStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die DepthRange ähnelt.
        /// </summary>
        public static string labelDepthRange {
            get {
                return ResourceManager.GetString("labelDepthRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Description ähnelt.
        /// </summary>
        public static string labelDescription {
            get {
                return ResourceManager.GetString("labelDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Detection mode ähnelt.
        /// </summary>
        public static string labelDetectionMode {
            get {
                return ResourceManager.GetString("labelDetectionMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Gestures ähnelt.
        /// </summary>
        public static string labelGestures {
            get {
                return ResourceManager.GetString("labelGestures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Height ähnelt.
        /// </summary>
        public static string labelHeight {
            get {
                return ResourceManager.GetString("labelHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Invert ähnelt.
        /// </summary>
        public static string labelInvert {
            get {
                return ResourceManager.GetString("labelInvert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Loaded workflow ähnelt.
        /// </summary>
        public static string labelLoadedWorkflow {
            get {
                return ResourceManager.GetString("labelLoadedWorkflow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Matching tolerance: ähnelt.
        /// </summary>
        public static string labelMatchingTolerance {
            get {
                return ResourceManager.GetString("labelMatchingTolerance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Maximal depth ähnelt.
        /// </summary>
        public static string labelMaxDepth {
            get {
                return ResourceManager.GetString("labelMaxDepth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die MinArea (onAdding): ähnelt.
        /// </summary>
        public static string labelMinAreaonAdding {
            get {
                return ResourceManager.GetString("labelMinAreaonAdding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die MinArea (Subtraction): ähnelt.
        /// </summary>
        public static string labelMinAreaSubtraction {
            get {
                return ResourceManager.GetString("labelMinAreaSubtraction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Minimal depth ähnelt.
        /// </summary>
        public static string labelMinDepth {
            get {
                return ResourceManager.GetString("labelMinDepth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die MinValueChange (add): ähnelt.
        /// </summary>
        public static string labelMinValueChangeAdd {
            get {
                return ResourceManager.GetString("labelMinValueChangeAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die MinValueChange (sub): ähnelt.
        /// </summary>
        public static string labelMinValueChangeSub {
            get {
                return ResourceManager.GetString("labelMinValueChangeSub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Moving Threshold ähnelt.
        /// </summary>
        public static string labelMovingThreshold {
            get {
                return ResourceManager.GetString("labelMovingThreshold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Name ähnelt.
        /// </summary>
        public static string labelName {
            get {
                return ResourceManager.GetString("labelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Name of work step ähnelt.
        /// </summary>
        public static string labelNameOfWorkStep {
            get {
                return ResourceManager.GetString("labelNameOfWorkStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Auth Token ähnelt.
        /// </summary>
        public static string labelNetworkAuthToken {
            get {
                return ResourceManager.GetString("labelNetworkAuthToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Network Settings ähnelt.
        /// </summary>
        public static string labelNetworkSettings {
            get {
                return ResourceManager.GetString("labelNetworkSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Table name ähnelt.
        /// </summary>
        public static string labelNetworkTableName {
            get {
                return ResourceManager.GetString("labelNetworkTableName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Next ähnelt.
        /// </summary>
        public static string labelNext {
            get {
                return ResourceManager.GetString("labelNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No recognition ähnelt.
        /// </summary>
        public static string labelNoRecognition {
            get {
                return ResourceManager.GetString("labelNoRecognition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Not playing ähnelt.
        /// </summary>
        public static string labelNotPlaying2DRecord {
            get {
                return ResourceManager.GetString("labelNotPlaying2DRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Not Playing ähnelt.
        /// </summary>
        public static string labelNotPlaying3DRecord {
            get {
                return ResourceManager.GetString("labelNotPlaying3DRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Not recording 2D ähnelt.
        /// </summary>
        public static string labelNotRecording2D {
            get {
                return ResourceManager.GetString("labelNotRecording2D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Not recording 3D ähnelt.
        /// </summary>
        public static string labelNotRecording3D {
            get {
                return ResourceManager.GetString("labelNotRecording3D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Not recording profile ähnelt.
        /// </summary>
        public static string labelNotRecordingProfile {
            get {
                return ResourceManager.GetString("labelNotRecordingProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No workflow loaded ähnelt.
        /// </summary>
        public static string labelNoWorkflowLoaded {
            get {
                return ResourceManager.GetString("labelNoWorkflowLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Offset ähnelt.
        /// </summary>
        public static string labelOffset {
            get {
                return ResourceManager.GetString("labelOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die parts produced ähnelt.
        /// </summary>
        public static string labelPartsProduced {
            get {
                return ResourceManager.GetString("labelPartsProduced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Path to save image to: ähnelt.
        /// </summary>
        public static string labelPathToSaveImageTo {
            get {
                return ResourceManager.GetString("labelPathToSaveImageTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die % of pixels to match: ähnelt.
        /// </summary>
        public static string labelPercentOfPixelMatch {
            get {
                return ResourceManager.GetString("labelPercentOfPixelMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die % to Trigger ähnelt.
        /// </summary>
        public static string labelPercentWithinBoundTrigger {
            get {
                return ResourceManager.GetString("labelPercentWithinBoundTrigger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Previous ähnelt.
        /// </summary>
        public static string labelPrevious {
            get {
                return ResourceManager.GetString("labelPrevious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Server base address ähnelt.
        /// </summary>
        public static string labelServerBaseAddress {
            get {
                return ResourceManager.GetString("labelServerBaseAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Height ähnelt.
        /// </summary>
        public static string labelSettingsHeight {
            get {
                return ResourceManager.GetString("labelSettingsHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Smoothing ähnelt.
        /// </summary>
        public static string labelSmoothing {
            get {
                return ResourceManager.GetString("labelSmoothing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Smoothing Steps ähnelt.
        /// </summary>
        public static string labelSmoothingSteps {
            get {
                return ResourceManager.GetString("labelSmoothingSteps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Status: ähnelt.
        /// </summary>
        public static string labelStatus {
            get {
                return ResourceManager.GetString("labelStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Stopping Threshold ähnelt.
        /// </summary>
        public static string labelStoppingThreshold {
            get {
                return ResourceManager.GetString("labelStoppingThreshold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die End Time: ähnelt.
        /// </summary>
        public static string labelTimeEnd {
            get {
                return ResourceManager.GetString("labelTimeEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Time Span: ähnelt.
        /// </summary>
        public static string labelTimeSpan {
            get {
                return ResourceManager.GetString("labelTimeSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Start Time: ähnelt.
        /// </summary>
        public static string labelTimeStart {
            get {
                return ResourceManager.GetString("labelTimeStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Width ähnelt.
        /// </summary>
        public static string labelWidth {
            get {
                return ResourceManager.GetString("labelWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Work steps: ähnelt.
        /// </summary>
        public static string labelWorkSteps {
            get {
                return ResourceManager.GetString("labelWorkSteps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Group ähnelt.
        /// </summary>
        public static string listViewGroup {
            get {
                return ResourceManager.GetString("listViewGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ID ähnelt.
        /// </summary>
        public static string listViewID {
            get {
                return ResourceManager.GetString("listViewID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Image ähnelt.
        /// </summary>
        public static string listViewImage {
            get {
                return ResourceManager.GetString("listViewImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Message ähnelt.
        /// </summary>
        public static string listViewMessage {
            get {
                return ResourceManager.GetString("listViewMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Path ähnelt.
        /// </summary>
        public static string listViewPath {
            get {
                return ResourceManager.GetString("listViewPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die About ähnelt.
        /// </summary>
        public static string menuItemAbout {
            get {
                return ResourceManager.GetString("menuItemAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Calibrate Kinect... ähnelt.
        /// </summary>
        public static string menuItemCalibrateKinect {
            get {
                return ResourceManager.GetString("menuItemCalibrateKinect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Calibrate Table... ähnelt.
        /// </summary>
        public static string menuItemCalibrateTable {
            get {
                return ResourceManager.GetString("menuItemCalibrateTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Close ähnelt.
        /// </summary>
        public static string menuItemClose {
            get {
                return ResourceManager.GetString("menuItemClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Delete ähnelt.
        /// </summary>
        public static string menuItemDelete {
            get {
                return ResourceManager.GetString("menuItemDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Edit ähnelt.
        /// </summary>
        public static string menuItemEdit {
            get {
                return ResourceManager.GetString("menuItemEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Edit Custom Scene ähnelt.
        /// </summary>
        public static string menuItemEditCustomScene {
            get {
                return ResourceManager.GetString("menuItemEditCustomScene", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Edit Scene ähnelt.
        /// </summary>
        public static string menuItemEditScene {
            get {
                return ResourceManager.GetString("menuItemEditScene", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die _Edit Workflow ähnelt.
        /// </summary>
        public static string menuItemEditWorkflow {
            get {
                return ResourceManager.GetString("menuItemEditWorkflow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die English ähnelt.
        /// </summary>
        public static string menuItemEnglish {
            get {
                return ResourceManager.GetString("menuItemEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die E_xit ähnelt.
        /// </summary>
        public static string menuItemExit {
            get {
                return ResourceManager.GetString("menuItemExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die _File ähnelt.
        /// </summary>
        public static string menuItemFile {
            get {
                return ResourceManager.GetString("menuItemFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die German ähnelt.
        /// </summary>
        public static string menuItemGerman {
            get {
                return ResourceManager.GetString("menuItemGerman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Help ähnelt.
        /// </summary>
        public static string menuItemHelp {
            get {
                return ResourceManager.GetString("menuItemHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Language ähnelt.
        /// </summary>
        public static string menuItemLanguage {
            get {
                return ResourceManager.GetString("menuItemLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Load scene ähnelt.
        /// </summary>
        public static string menuItemLoadScene {
            get {
                return ResourceManager.GetString("menuItemLoadScene", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die _Load Workflow ähnelt.
        /// </summary>
        public static string menuItemLoadWorkflow {
            get {
                return ResourceManager.GetString("menuItemLoadWorkflow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die New Scene ähnelt.
        /// </summary>
        public static string menuItemNewScene {
            get {
                return ResourceManager.GetString("menuItemNewScene", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die _New Workflow ähnelt.
        /// </summary>
        public static string menuItemNewWorkflow {
            get {
                return ResourceManager.GetString("menuItemNewWorkflow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Options ähnelt.
        /// </summary>
        public static string menuItemOptions {
            get {
                return ResourceManager.GetString("menuItemOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save ähnelt.
        /// </summary>
        public static string menuItemSave {
            get {
                return ResourceManager.GetString("menuItemSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save Scene ähnelt.
        /// </summary>
        public static string menuItemSaveScene {
            get {
                return ResourceManager.GetString("menuItemSaveScene", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Scenes ähnelt.
        /// </summary>
        public static string menuItemScenes {
            get {
                return ResourceManager.GetString("menuItemScenes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Settings... ähnelt.
        /// </summary>
        public static string menuItemSettings {
            get {
                return ResourceManager.GetString("menuItemSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Assembly area ähnelt.
        /// </summary>
        public static string radioButtonAssemblyArea {
            get {
                return ResourceManager.GetString("radioButtonAssemblyArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Blob ähnelt.
        /// </summary>
        public static string radioButtonBlob {
            get {
                return ResourceManager.GetString("radioButtonBlob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Contour ähnelt.
        /// </summary>
        public static string radioButtonContour {
            get {
                return ResourceManager.GetString("radioButtonContour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Drawing area ähnelt.
        /// </summary>
        public static string radioButtonDrawingArea {
            get {
                return ResourceManager.GetString("radioButtonDrawingArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die On ähnelt.
        /// </summary>
        public static string radioButtonOn {
            get {
                return ResourceManager.GetString("radioButtonOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Scan  table ähnelt.
        /// </summary>
        public static string radioButtonScanTable {
            get {
                return ResourceManager.GetString("radioButtonScanTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Static ähnelt.
        /// </summary>
        public static string radioButtonStatic {
            get {
                return ResourceManager.GetString("radioButtonStatic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 2DTouch ähnelt.
        /// </summary>
        public static string tabItem2DTouch {
            get {
                return ResourceManager.GetString("tabItem2DTouch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Assembly zone ähnelt.
        /// </summary>
        public static string tabItemAssemblyZone {
            get {
                return ResourceManager.GetString("tabItemAssemblyZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Boxes ähnelt.
        /// </summary>
        public static string tabItemBoxes {
            get {
                return ResourceManager.GetString("tabItemBoxes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Debug ähnelt.
        /// </summary>
        public static string tabItemDebug {
            get {
                return ResourceManager.GetString("tabItemDebug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Editor ähnelt.
        /// </summary>
        public static string tabItemEditor {
            get {
                return ResourceManager.GetString("tabItemEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Gestures ähnelt.
        /// </summary>
        public static string tabItemGestures {
            get {
                return ResourceManager.GetString("tabItemGestures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Gestures Debug ähnelt.
        /// </summary>
        public static string tabItemGesturesDebug {
            get {
                return ResourceManager.GetString("tabItemGesturesDebug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Objects ähnelt.
        /// </summary>
        public static string tabItemObjects {
            get {
                return ResourceManager.GetString("tabItemObjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die PBD ähnelt.
        /// </summary>
        public static string tabItemPBD {
            get {
                return ResourceManager.GetString("tabItemPBD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Scenes ähnelt.
        /// </summary>
        public static string tabItemScenes {
            get {
                return ResourceManager.GetString("tabItemScenes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Settings ähnelt.
        /// </summary>
        public static string tabItemSettings {
            get {
                return ResourceManager.GetString("tabItemSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Survey ähnelt.
        /// </summary>
        public static string tabItemSurvey {
            get {
                return ResourceManager.GetString("tabItemSurvey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Video ähnelt.
        /// </summary>
        public static string tabItemVideo {
            get {
                return ResourceManager.GetString("tabItemVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Visualization ähnelt.
        /// </summary>
        public static string tabItemVisualization {
            get {
                return ResourceManager.GetString("tabItemVisualization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Workflow ähnelt.
        /// </summary>
        public static string tabItemWorkflow {
            get {
                return ResourceManager.GetString("tabItemWorkflow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Calibration ähnelt.
        /// </summary>
        public static string titleCalibrationDialog {
            get {
                return ResourceManager.GetString("titleCalibrationDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Create Workflow ähnelt.
        /// </summary>
        public static string titleCreateWorkflowDialog {
            get {
                return ResourceManager.GetString("titleCreateWorkflowDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Settings ähnelt.
        /// </summary>
        public static string titleSettingsWindow {
            get {
                return ResourceManager.GetString("titleSettingsWindow", resourceCulture);
            }
        }
    }
}
